# Generated by Django 5.2 on 2025-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Category1')),
                ('slug', models.SlugField(unique=True, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Category1',
                'verbose_name_plural': 'categor',
            },
        ),
    ]
