# Generated by Django 5.2 on 2025-10-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_cartitem_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
