# Generated by Django 5.2 on 2025-09-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category1'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categor', to='store.category1'),
        ),
    ]
