# Generated by Django 5.2 on 2025-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_products_category1_alter_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category1',
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
